name: Autograding Tests
"on":
    - workflow_dispatch
    - push
    - repository_dispatch
permissions:
    checks: write
    actions: read
    contents: read
jobs:
    run-autograding-tests:
        runs-on: ubuntu-latest
        if: github.actor != 'github-classroom[bot]'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Style
              id: style
              uses: classroom-resources/autograding-command-grader@v1
              with:
                  test-name: Style
                  timeout: 10
                  setup-command: pip3 install -qr requirements.txt; pip3 install
                      darglint==1.8.0; pip3 install flake8==5.0.4 mypy==1.13.0
                  command:
                      flake8 --ignore "N801, E203, E266, E501, W503, F812, E741, N803,
                      N802, N806" minitorch/ tests/ project/; mypy minitorch/*
            - name: Task 4.1
              id: task-4-1
              uses: classroom-resources/autograding-command-grader@v1
              with:
                  test-name: Task 4.1
                  timeout: 10
                  setup-command: pip3 install -qr requirements.txt
                  command: pytest --verbose -m task4_1
            - name: Task 4.2
              id: task-4-2
              uses: classroom-resources/autograding-command-grader@v1
              with:
                  test-name: Task 4.2
                  timeout: 10
                  setup-command: pip3 install -qr requirements.txt
                  command: pytest --verbose -m task4_2
            - name: Task 4.3
              id: task-4-3
              uses: classroom-resources/autograding-command-grader@v1
              with:
                  test-name: Task 4.3
                  timeout: 10
                  setup-command: pip3 install -qr requirements.txt
                  command: pytest --verbose -m task4_3
            - name: Task 4.4
              id: task-4-4
              uses: classroom-resources/autograding-command-grader@v1
              with:
                  test-name: Task 4.4
                  timeout: 10
                  setup-command: pip3 install -qr requirements.txt
                  command: pytest --verbose -m task4_4
            - name: Autograding Reporter
              uses: classroom-resources/autograding-grading-reporter@v1
              env:
                  STYLE_RESULTS: "${{steps.style.outputs.result}}"
                  TASK-4-1_RESULTS: "${{steps.task-4-1.outputs.result}}"
                  TASK-4-2_RESULTS: "${{steps.task-4-2.outputs.result}}"
                  TASK-4-3_RESULTS: "${{steps.task-4-3.outputs.result}}"
                  TASK-4-4_RESULTS: "${{steps.task-4-4.outputs.result}}"
              with:
                  runners: style,task-4-1,task-4-2,task-4-3,task-4-4
